version: 0.2         
phases:
  install:
    runtime-versions:
      golang: 1.12
  pre_build:
    commands:
      - echo Building the AWS for Fluent Bit image
  build:
    commands:
      # Command to build your project
      - make release

      # List the docker images 
      - docker images

      # Push the image to ECR in the same account and same region the pipeline is hosted.
      - aws ecr get-login-password --region us-west-2| docker login --username AWS --password-stdin 957584016365.dkr.ecr.us-west-2.amazonaws.com
      - aws ecr create-repository --repository-name amazon/aws-for-fluent-bit-test --image-scanning-configuration scanOnPush=true --region us-west-2  || true
      - architecture=$(docker inspect --format='{{.Architecture}}'  amazon/aws-for-fluent-bit)
      - docker tag amazon/aws-for-fluent-bit:latest 957584016365.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-for-fluent-bit-test:$architecture
      - docker push 957584016365.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-for-fluent-bit-test:$architecture
artifacts:
  files:
    - '**/*'